[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#CB202D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#1C1C1C"
font = "sans serif"
